language: java

jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_KEY
    app: castlemock
  on:
    branch: master
    jdk: openjdk10

notifications:
  slack: $SLACK_KEY