/*
 * Copyright 2015 Karl Dahlgren
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.fortmocks.core.basis.model;

/**
 * The ServiceResult is a container class for the output message generated by the service classes.
 * @author Karl Dahlgren
 * @since 1.0
 */
public class ServiceResult<O extends Output> {

    private O output;

    /**
     * Default constructor for the ServiceResult
     * @param output The output message generated by a service class
     */
    public ServiceResult(O output) {
        this.output = output;
    }

    /**
     * Get the output message
     * @return The output message
     */
    public O getOutput() {
        return output;
    }

    /**
     * Sets a new value for the output message
     * @param output The new output message that will replace the old one
     */
    public void setOutput(O output) {
        this.output = output;
    }
}
